name: Publish to COPR

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy_copr:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v3
      - name: Create spec file dir
        run: mkdir -p ./pkg/
      - name: Build spec file
        run: >-
          sed -i "s/REPLACE_VERSION/$(cat package.json | grep -E '"version": "[0-9\.]+"' -o | grep -E "[0-9\.]+" -o)/" ./pkg/hhd-ui.spec
      - name: Publish to COPR repo
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:hhd-dev/hhd-ui-copr.git
          BRANCH: main
          FOLDER: pkg
          SSH_PRIVATE_KEY: ${{ secrets.COPR_SSH_PRIVATE_KEY }}
          MESSAGE: update to '${{ github.event.release.name }}'
          SKIP_EMPTY_COMMITS: true
          # Do not clear any files
          CLEAR_GLOBS_FILE: .github/workflows/copr_glob.txt