name: Publish to AUR

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy_aur:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v3
      - name: Use proper version in PKGBUILD
        run: >-
          sed -i "s/pkgver=VERSION/pkgver=$(cat package.json | grep -E '"version": "[0-9\.]+"' -o | grep -E "[0-9\.]+" -o)/" ./aur/PKGBUILD
      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.0
        with:
          pkgname: hhd-ui
          pkgbuild: ./aur/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: update to '${{ github.event.release.name }}'
          allow_empty_commits: false
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
          updpkgsums: true
          # assets: >-
          #   ./aur/hhd-ui.desktop
          #   ./aur/hhd-ui.sh